version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      development-toolchain:
        patterns: ['@cloudflare/*', 'vite*', 'vitest', 'wrangler', 'typescript']
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
