// Generated by scripts/generate.mjs. Do not edit this file directly.
import { plugin as armaReforger } from '@gridora/plugin-arma-reforger'
import { plugin as valheim } from '@gridora/plugin-valheim'

export const generatedPluginBundles = [armaReforger, valheim] as const
