import { readFile, writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'

const packageRoot = fileURLToPath(new URL('../', import.meta.url))
const sources = JSON.parse(await readFile(`${packageRoot}registry.sources.json`, 'utf8'))
if (
  !Array.isArray(sources) ||
  sources.length < 2 ||
  sources.some(
    (source) =>
      typeof source !== 'object' ||
      source === null ||
      !/^@gridora\/plugin-[a-z0-9-]+$/.test(source.package) ||
      !/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(source.export) ||
      !/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(source.local),
  ) ||
  new Set(sources.map((source) => source.package)).size !== sources.length ||
  new Set(sources.map((source) => source.local)).size !== sources.length
)
  throw new Error('plugin registry sources are invalid or ambiguous')

const imports = sources
  .map((source) => `import { ${source.export} as ${source.local} } from '${source.package}'`)
  .join('\n')
const output = `// Generated by scripts/generate.mjs. Do not edit this file directly.\n${imports}\n\nexport const generatedPluginBundles = [${sources.map((source) => source.local).join(', ')}] as const\n`
const target = `${packageRoot}src/registry.generated.ts`
if (process.argv.includes('--check')) {
  const current = await readFile(target, 'utf8').catch(() => '')
  if (current !== output) throw new Error('plugin registry output is stale; run pnpm generate')
} else {
  await writeFile(target, output)
}
